### PR TITLE
Add itunes_image to Items::Item

### PR DESCRIPTION
**Pull request by ianrandmckenzie**
References https://github.com/ruby/rss/issues/8

### CODE REVIEW

**Comment by ianrandmckenzie** [comment]
Sorry about this taking 3 months. I got severely sidetracked by a bunch of different projects.

**Comment by kou** [comment]
The failure is caused by REXML.
I've released a new version of REXML and restarted the failed job.
Now CI is green.

I'll review this.

**Comment by ianrandmckenzie** [comment]
Sounds good! I'm ready to fix any mistakes once you've reviewed.

**Comment by kou** [comment]
Could you add tests?
Or should I take over it?

**Comment by ianrandmckenzie** [comment]
I'm happy to add tests. I just realized the reason I had put off submitting a PR for so long was that I hadn't. Then, by the time I submitted the PR, I evidently forgot that step. I will add tests and loop back with you.

**Comment by kou** [comment]
Thanks!
If you have any trouble, feel free to ask me here.

**Comment by ianrandmckenzie** [comment]
I think these tests passed? I ran the test suite before adding my own tests and 312 passed. I added my tests and ran the suite again and it still said 312 passed. The number didn't change. I assume because everything passed, I'm good. But, I expected the number 312 to go up by a little bit. It did not. Happy to make fixes if anything needs to be changed.

**Comment by ianrandmckenzie** [comment]
@kou I am having a "staycation" this week and have lots of time to contribute to open source. This week would be a good time to let me know if I need to make any fixes. Thanks!

**Comment by kou** [comment]
Sorry for my late response...
I hope that I can review this in this week...

**Comment by ianrandmckenzie** [comment]
Thank you, @kou! This is the first time my contribution to open source was merged, I'm so happy it was to the Ruby project. Rails is my bread and butter, I'm so happy I could do my part in a small way.

**Comment by kou** [comment]
Great!
We're waiting for your next contribution! :-)

**Pull request merged**
